- job:
    name: run-tests
    nodeset:
      nodes:
        - name: ubuntu
          label: ubuntu-jammy
    run: playbooks/run-tests.yaml

- project:
    default-branch: main
    check:
      jobs:
        - run-tests
    gate:
      jobs:
        - run-tests