- hosts: all
  become: true

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install test dependencies
      pip:
        requirements: test-requirements.txt
        executable: pip3
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: show repo contents
      shell: ls -la

    - name: check python version
      shell: python3 --version

    - name: run test file
      shell: python3 test_app.py
      args:
        chdir: "{{ zuul.project.src_dir }}"