- hosts: all
  tasks:
    - name: Install pip (Ubuntu)
      shell: |
        python3 -m ensurepip --upgrade || true
        python3 -m pip install --upgrade pip

    - name: Install test dependencies
      shell: pip3 install -r test-requirements.txt

    - name: show repo contents
      shell: ls -la

    - name: check python version
      shell: python3 --version

    - name: run test file
      shell: python3 test_app.py